apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envoy:envoy:priviledged
  namespace: envoy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: envoy
  namespace: envoy
