apiVersion: batch/v1
kind: Job
metadata:
  name: run-mysql-benchmark
  namespace: mysql
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccount: mysql
      securityContext:
        runAsUser: 0
      containers:
      - name: run-mysql-benchmark
        image: quay.io/kinvolk/benchmark-mysql
        imagePullPolicy: Always
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        env:
        - name: THREADS
          value: "{{ .Values.threads }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.myqlDatabase }}"
        - name: MYSQL_ITERATIONS
          value: "{{ .Values.mysqlIterations }}"
        - name: PUSHGATEWAY_URL
          value: "{{ .Values.pushgatewayURL }}"
        - name: CLOUD
          value: "{{ .Values.cloud }}"
        - name: INSTANCE
          value: "{{ .Values.instance }}"
        - name: JOBNAME
          value: "{{ .Values.jobname }}"
        command:
        - sh
        args:
        - -c
        - '/usr/local/bin/run-benchmark.sh'
        volumeMounts:
        - mountPath: /tmp/
          name: tmp-dir
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      automountServiceAccountToken: false
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{ end -}}
      {{- if .Values.tolerations }}
      tolerations:
        {{- with .Values.tolerations }}
{{ toYaml . | indent 6 }}
        {{- end }}
      {{ end }}
